version: '2.15'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: order-matching-backend
    ports:
      - '8080:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - order-matching-network

  frontend:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    container_name: order-matching-frontend
    ports:
      - '5500:80'
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8080
    networks:
      - order-matching-network

networks:
  order-matching-network:
    driver: bridge
